# Generated by Django 4.2.7 on 2024-07-06 21:25

import builtins
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='created_by',
            field=models.ForeignKey(default=builtins.print, on_delete=django.db.models.deletion.CASCADE, related_name='created_organisations', to='monapp.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='users',
            field=models.ManyToManyField(related_name='organisations', to='monapp.user'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='orgId',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
    ]
