# Generated by Django 5.0.6 on 2024-07-07 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0002_organisation_created_by_organisation_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='created_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_organisations', to='monapp.user'),
        ),
    ]
